# Generated by Django 3.2.24 on 2024-03-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestManyToMany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hobby', models.ManyToManyField(related_name='testmanytomany_hobby', to='home.Hobby')),
            ],
        ),
    ]
